### ISSUE TITLE
Should the /tutorials/_build/ directory be included in .gitignore?

### ISSUE THREAD

**Issue by emamd** [palewire/first-visual-story#103]
trying to commit an update to the readme right now and seeing a lot of updates to files in /tutorials/_build/html/.doctrees, which seems weird

**Comment by palewire** [comment]
yes, it should be in the gitignore. You are right.

**Comment by emamd** [comment]
I'll add!

**Comment by emamd** [comment]
err, wait, looks like the [docs.yml ](https://github.com/palewire/first-visual-story/blob/main/.github/workflows/docs.yml#L21)file specifies that `tutorial/_build/html` is the folder that should be used to actually build the site? whoops

**Comment by emamd** [comment]
Updated this to ignore `tutorial/_build/html/*.doctrees`, which it seems are not needed

**Comment by palewire** [comment]
The global ignore of the dir is okay. The action will rebuild the directory on the file as part of the rollup process. So it doesn't matter if it's missing from github, and in fact a good thing.
