### ISSUE TITLE
Do we want to specify that people should be on a specific node version? 

### ISSUE THREAD

**Issue by emamd** [palewire/first-visual-story#104]
I don't think this is mentioned in the repo, thought about it when I got to the [npm install instructions](https://palewi.re/docs/first-visual-story/framework.html#id2). Might be worth saying that people should be running the LTS Node version when seeing `node --version`, or even suggesting people use `nvm`. The latter might be a step of extra complication but I could add a note about it

**Comment by palewire** [comment]
I think we hand that [here](https://palewi.re/docs/first-visual-story/prereqs.html#node-js)
